CREATE DATABASE INFORMATION;
SHOW DATABASES;
USE INFORMATION;

CREATE TABLE STUDENT
(
ID INTEGER PRIMARY KEY,
NAME VARCHAR(20),
DEPARTMENT VARCHAR(20)
);

SHOW TABLES;
SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUES(1, 'ASHWINI' , 'IT');
INSERT INTO STUDENT (ID, DEPARTMENT, NAME) VALUES (2, 'SHUBHAM', 'IT');
INSERT INTO STUDENT (ID, DEPARTMENT, NAME) VALUES (3, 'IT', 'KARTIK');

ALTER TABLE STUDENT ADD JOIN_DATE DATE;
ALTER TABLE STUENT MODIFY NAME VARCHAR(30);
ALTER TABLE STUDENT RENAME TO STUD;
ALTER TABLE STUD RENAME TO STUDENT;

SHOW TABLES;

ALTER TABLE STUDENT DROP COLUMN JOIN_DATE;

TRUNCATE TABLE STUDENT;
DROP TABLE STUDENT;

RENAME TABLE STUDENT TO STUD;
RENAME TABLE STUD TO STUDENT;

INSERT INTO STUDENT VALUES (4 , 'VIKAS', 'COMPUTER');
INSERT INTO STUDENT VALUES (5 , 'ALISHA', 'COMPUTER');

UPDATE STUDENT SET DEPARTMENT='IT' WHERE ID =4;
UPDATE STUDENT SET DEPARTMENT='COMPUTER' WHERE ID=4;

DELETE FROM STUDENT WHERE ID=3;

SELECT NAME FROM STUDENT;
SELECT DEPARTMENT FROM STUDENT;
SELECT 1 FROM STUDENT;
SELECT 'NAME OF THE STUDENT IS' , NAME FROM STUDENT;
